/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import config.DatabaseConfig;
import java.awt.BorderLayout;
import java.awt.Image;
import repository.supplierRepo;
import usecase.supplierUc;
import usecase.userUc;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import repository.brandsRepo;
import repository.usersRepo;

/**
 *
 * @author ADMINPUSING-PC
 */
public class aMainFrame extends javax.swing.JFrame {

    private SupplierManagementGUI supplierPanel;
    private aDashboard dashboardPanel;
    private BrandManagementGUI brandPanel;
    private ItemManagementGUI itemPanel;
    private StockManagementGUI stockPanel;
    private TransactionManagementGUI transactionPanel;
    private UserManagement userPanel;
    private ReportManagementGUI reportPanel;
    private Connection conn;

    /**
     * Creates new form Dashboard
     */
    public aMainFrame(Connection conn) {
        initComponents();
        this.dashboardPanel = new aDashboard(conn);
        this.supplierPanel = new SupplierManagementGUI(conn);
        this.brandPanel = new BrandManagementGUI(conn);
        this.itemPanel = new ItemManagementGUI(conn);
        this.stockPanel = new StockManagementGUI(conn);
        this.reportPanel = new ReportManagementGUI(conn);
        this.transactionPanel = new TransactionManagementGUI(conn);
        this.userPanel = new UserManagement(conn);

        this.conn = conn;

        mainPanel.add(dashboardPanel);
        mainPanel.add(supplierPanel);
        mainPanel.add(brandPanel);
        mainPanel.add(itemPanel);
        mainPanel.add(stockPanel);
        mainPanel.add(transactionPanel);
        mainPanel.add(userPanel);
        mainPanel.add(reportPanel);

        userPanel.setVisible(false);
        transactionPanel.setVisible(false);
        supplierPanel.setVisible(false);
        brandPanel.setVisible(false);
        itemPanel.setVisible(false);
        stockPanel.setVisible(false);
        reportPanel.setVisible(false);
        dashboardPanel.setVisible(true);

    }

    private void unvisiblePanel() {
        transactionPanel.setVisible(false);
        supplierPanel.setVisible(false);
        dashboardPanel.setVisible(false);
        brandPanel.setVisible(false);
        itemPanel.setVisible(false);
        stockPanel.setVisible(false);
        userPanel.setVisible(false);
        reportPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnBrand = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnStockBarang = new javax.swing.JButton();
        btnTransaksiPenjualan = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        mainPanel = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
                g2d.setRenderingHint(java.awt.RenderingHints.KEY_RENDERING,
                        java.awt.RenderingHints.VALUE_RENDER_QUALITY);
                java.awt.Color color1 = new java.awt.Color(0, 153, 153);
                java.awt.Color color2 = new java.awt.Color(0, 102, 102);
                java.awt.GradientPaint gp = new java.awt.GradientPaint(0, 0, color1, 0, getHeight(), color2);
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 204, 102))); // Gold/Orange
                                                                                                                       // accent
                                                                                                                       // line
        jPanel2.setForeground(new java.awt.Color(204, 255, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(1400, 115));

        btnHome.setBackground(new java.awt.Color(0, 153, 153));
        btnHome.setForeground(new java.awt.Color(0, 153, 153));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/roxy2.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setFocusPainted(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setName(""); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnBrand.setBackground(new java.awt.Color(0, 153, 153));
        btnBrand.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBrand.setForeground(new java.awt.Color(255, 255, 255));
        btnBrand.setText("BRAND");
        btnBrand.setBorder(null);
        btnBrand.setBorderPainted(false);
        btnBrand.setContentAreaFilled(false);
        btnBrand.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandActionPerformed(evt);
            }
        });

        btnSupplier.setBackground(new java.awt.Color(0, 153, 153));
        btnSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnSupplier.setText("SUPPLIER");
        btnSupplier.setBorder(null);
        btnSupplier.setBorderPainted(false);
        btnSupplier.setContentAreaFilled(false);
        btnSupplier.setFocusPainted(false);
        btnSupplier.setFocusable(false);
        btnSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });

        btnBarang.setBackground(new java.awt.Color(0, 153, 153));
        btnBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnBarang.setText("ITEM");
        btnBarang.setBorder(null);
        btnBarang.setBorderPainted(false);
        btnBarang.setContentAreaFilled(false);
        btnBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });

        btnStockBarang.setBackground(new java.awt.Color(0, 153, 153));
        btnStockBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStockBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnStockBarang.setText("STOCK");
        btnStockBarang.setBorder(null);
        btnStockBarang.setBorderPainted(false);
        btnStockBarang.setContentAreaFilled(false);
        btnStockBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStockBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockBarangActionPerformed(evt);
            }
        });

        btnTransaksiPenjualan.setBackground(new java.awt.Color(0, 153, 153));
        btnTransaksiPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTransaksiPenjualan.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaksiPenjualan.setText("TRANSACTION");
        btnTransaksiPenjualan.setBorder(null);
        btnTransaksiPenjualan.setBorderPainted(false);
        btnTransaksiPenjualan.setContentAreaFilled(false);
        btnTransaksiPenjualan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaksiPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiPenjualanActionPerformed(evt);
            }
        });

        btnReport.setBackground(new java.awt.Color(0, 153, 153));
        btnReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReport.setForeground(new java.awt.Color(255, 255, 255));
        btnReport.setText("REPORT");
        btnReport.setBorder(null);
        btnReport.setBorderPainted(false);
        btnReport.setContentAreaFilled(false);
        btnReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnUser.setBackground(new java.awt.Color(0, 153, 153));
        btnUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUser.setForeground(new java.awt.Color(255, 255, 255));
        btnUser.setText("USER");
        btnUser.setBorder(null);
        btnUser.setBorderPainted(false);
        btnUser.setContentAreaFilled(false);
        btnUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        btnLogout = new javax.swing.JButton();
        btnLogout.setBackground(new java.awt.Color(0, 153, 153));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
                new Login1(conn).setVisible(true);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 207,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSupplier)
                                .addGap(20, 20, 20)
                                .addComponent(btnBrand)
                                .addGap(20, 20, 20)
                                .addComponent(btnBarang)
                                .addGap(20, 20, 20)
                                .addComponent(btnStockBarang)
                                .addGap(20, 20, 20)
                                .addComponent(btnTransaksiPenjualan)
                                .addGap(20, 20, 20)
                                .addComponent(btnReport)
                                .addGap(20, 20, 20)
                                .addComponent(btnUser)
                                .addGap(20, 20, 20)
                                .addComponent(btnLogout)
                                .addGap(40, 40, 40)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(34, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnStockBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnTransaksiPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 54,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 54,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 54,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 54,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)));

        mainPanel.setBackground(new java.awt.Color(250, 250, 250));
        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1400,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)));

        setSize(new java.awt.Dimension(1400, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        /*
         * jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
         * public void mouseClicked(java.awt.event.MouseEvent evt) {
         * supplierManagementGUI.setVisible(true);
         * dashboard.setVisible(false);
         * }
         * });
         */
    }// GEN-LAST:event_formWindowOpened

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHomeActionPerformed
        unvisiblePanel();
        dashboardPanel.setVisible(true);
    }// GEN-LAST:event_btnHomeActionPerformed

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_btnHomeMouseClicked

    private void btnBrandActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBrandActionPerformed
        unvisiblePanel();
        brandPanel.setVisible(true);
    }// GEN-LAST:event_btnBrandActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSupplierActionPerformed
        unvisiblePanel();
        supplierPanel.setVisible(true);
    }// GEN-LAST:event_btnSupplierActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBarangActionPerformed
        unvisiblePanel();
        itemPanel.setVisible(true);
    }// GEN-LAST:event_btnBarangActionPerformed

    private void btnStockBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnStockBarangActionPerformed
        // TODO add your handling code here:
        unvisiblePanel();
        stockPanel.setVisible(true);
    }// GEN-LAST:event_btnStockBarangActionPerformed

    private void btnTransaksiPenjualanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTransaksiPenjualanActionPerformed
        unvisiblePanel();
        transactionPanel.setVisible(true);
    }// GEN-LAST:event_btnTransaksiPenjualanActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        unvisiblePanel();
        reportPanel.setVisible(true);
    }// GEN-LAST:event_btnReportActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        unvisiblePanel();
        userPanel.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Connection conn = DatabaseConfig.connect();
                new aMainFrame(conn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnBrand;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnStockBarang;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JButton btnTransaksiPenjualan;
    private javax.swing.JButton btnUser;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLayeredPane mainPanel;
    // End of variables declaration//GEN-END:variables
}
