/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import config.DatabaseConfig;
import java.awt.Image;
import java.sql.Connection;
import javax.swing.ImageIcon;

/**
 *
 * @author yuga.irawan
 */
public class Menu extends javax.swing.JFrame {

    private SupplierManagementGUI supplierPanel;
    private aDashboard dashboardPanel;
    private BrandManagementGUI brandPanel;
    private ItemManagementGUI itemPanel;
    private StockManagementGUI stockPanel;
    private TransactionManagementGUI transactionPanel;
    private UserManagement userPanel;
    private ReportManagementGUI reportPanel;
    private Connection conn;
      
    /**
     * Creates new form Menu
     * @param conn
     */
    public Menu(Connection conn) {
        this.conn = conn;
        initComponents();
        
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        this.dashboardPanel = new aDashboard();
        this.supplierPanel = new SupplierManagementGUI(conn);
        this.brandPanel = new BrandManagementGUI(conn);
        this.itemPanel = new ItemManagementGUI(conn);
        this.stockPanel = new StockManagementGUI(conn);
        this.reportPanel = new ReportManagementGUI(conn);
        this.transactionPanel = new TransactionManagementGUI(conn);
        this.userPanel = new UserManagement(conn);

        mainPanel.add(dashboardPanel);
        mainPanel.add(supplierPanel);
        mainPanel.add(brandPanel);
        mainPanel.add(itemPanel);
        mainPanel.add(stockPanel);
        mainPanel.add(transactionPanel);
        mainPanel.add(userPanel);
        mainPanel.add(reportPanel);

//if (supplierPanel != null) mainPanel.add(supplierPanel);
//if (brandPanel != null) mainPanel.add(brandPanel);
//if (itemPanel != null) mainPanel.add(itemPanel);
//if (stockPanel != null) mainPanel.add(stockPanel);
//if (transactionPanel != null) mainPanel.add(transactionPanel);
//if (userPanel != null) mainPanel.add(userPanel);
//if (reportPanel != null) mainPanel.add(reportPanel);
        
        userPanel.setVisible(false);
        transactionPanel.setVisible(false);
        supplierPanel.setVisible(false);
        brandPanel.setVisible(false);
        itemPanel.setVisible(false);
        stockPanel.setVisible(false);
        reportPanel.setVisible(false);
        dashboardPanel.setVisible(true);
  
//if (userPanel != null) userPanel.setVisible(false);
//if (transactionPanel != null) transactionPanel.setVisible(false);
//if (supplierPanel != null) supplierPanel.setVisible(false);
//if (brandPanel != null) brandPanel.setVisible(false);
//if (itemPanel != null) itemPanel.setVisible(false);
//if (stockPanel != null) stockPanel.setVisible(false);
//if (reportPanel != null) reportPanel.setVisible(false);
//
//dashboardPanel.setVisible(true);

    }
    private void unvisiblePanel(){
        transactionPanel.setVisible(false);
        supplierPanel.setVisible(false);
        dashboardPanel.setVisible(false);
        brandPanel.setVisible(false);
        itemPanel.setVisible(false);
        stockPanel.setVisible(false);
        userPanel.setVisible(false);
        reportPanel.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSupplier = new javax.swing.JButton();
        btnBrand = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnStockBarang = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        mainPanel = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        btnHome.setBackground(new java.awt.Color(0, 0, 255));
        btnHome.setForeground(new java.awt.Color(0, 0, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/roxy2.png"))); // NOI18N
        btnHome.setAlignmentY(0.0F);
        btnHome.setBorder(null);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(585, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        btnSupplier.setBackground(new java.awt.Color(255, 255, 153));
        btnSupplier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSupplier.setText("SUPPLIER");
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });

        btnBrand.setBackground(new java.awt.Color(255, 255, 153));
        btnBrand.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBrand.setText("BRAND");
        btnBrand.setPreferredSize(new java.awt.Dimension(85, 22));
        btnBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandActionPerformed(evt);
            }
        });

        btnBarang.setBackground(new java.awt.Color(255, 255, 153));
        btnBarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBarang.setText("ITEM");
        btnBarang.setPreferredSize(new java.awt.Dimension(85, 22));
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });

        btnStockBarang.setBackground(new java.awt.Color(255, 255, 153));
        btnStockBarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStockBarang.setText("STOCK BARANG");
        btnStockBarang.setPreferredSize(new java.awt.Dimension(85, 22));
        btnStockBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockBarangActionPerformed(evt);
            }
        });

        btnTransaksi.setBackground(new java.awt.Color(255, 255, 153));
        btnTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTransaksi.setText("TRANSAKSI");
        btnTransaksi.setPreferredSize(new java.awt.Dimension(85, 22));
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        btnReport.setBackground(new java.awt.Color(255, 255, 153));
        btnReport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReport.setText("REPORT");
        btnReport.setPreferredSize(new java.awt.Dimension(85, 22));
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnUser.setBackground(new java.awt.Color(255, 255, 153));
        btnUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUser.setText("USER");
        btnUser.setPreferredSize(new java.awt.Dimension(85, 22));
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBrand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(btnBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStockBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStockBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 153));
        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainPanel)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        unvisiblePanel();
        dashboardPanel.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        // TODO add your handling code here:
        unvisiblePanel();
        supplierPanel.setVisible(true);
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void btnBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandActionPerformed
        // TODO add your handling code here:
        unvisiblePanel();
       brandPanel.setVisible(true);
    }//GEN-LAST:event_btnBrandActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        // TODO add your handling code here:
        unvisiblePanel();
        itemPanel.setVisible(true);
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnStockBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockBarangActionPerformed
        // TODO add your handling code here:
        unvisiblePanel();
        stockPanel.setVisible(true);
    }//GEN-LAST:event_btnStockBarangActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
        unvisiblePanel();
        transactionPanel.setVisible(true);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        unvisiblePanel();
        reportPanel.setVisible(true);
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        unvisiblePanel();
        userPanel.setVisible(true);
    }//GEN-LAST:event_btnUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Connection conn = DatabaseConfig.connect();
                new Menu(conn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnBrand;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnStockBarang;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLayeredPane mainPanel;
    // End of variables declaration//GEN-END:variables
}
