/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

import repository.LogStockRepo;
import repository.supplierRepo;
import repository.transactionsRepo;
import config.DatabaseConfig;

/**
 *
 * @author ADMINPUSING-PC
 */
public class ReportManagementGUI extends javax.swing.JPanel {

    public ReportManagementGUI(Connection conn) {
        initComponents();
        helper.TableUtils.styleTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kategori = new javax.swing.JLabel();
        btnRiview = new javax.swing.JButton();
        report = new javax.swing.JLabel();
        cbKatExport = new javax.swing.JComboBox<>();
        periode = new javax.swing.JLabel();
        textFieldDate = new javax.swing.JTextField();
        hari = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 255, 204));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(621, 581));

        kategori.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        kategori.setForeground(new java.awt.Color(102, 102, 102));
        kategori.setText("Kategori");

        btnRiview.setBackground(new java.awt.Color(255, 153, 153));
        btnRiview.setForeground(new java.awt.Color(255, 255, 255));
        btnRiview.setText("Review");
        btnRiview.setBorder(null);
        btnRiview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiviewActionPerformed(evt);
            }
        });

        report.setFont(new java.awt.Font("Gill Sans", 0, 36)); // NOI18N
        report.setForeground(new java.awt.Color(102, 102, 102));
        report.setText("REPORT MANAGEMENT");

        cbKatExport.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "STOCK MASUK", "STOCK KELUAR", "MASTER SUPPLIER", "DATA TRANSAKSI", "" }));
        cbKatExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKatExportActionPerformed(evt);
            }
        });

        periode.setBackground(new java.awt.Color(255, 255, 255));
        periode.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        periode.setForeground(new java.awt.Color(102, 102, 102));
        periode.setText("Periode");

        textFieldDate.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDateActionPerformed(evt);
            }
        });
        textFieldDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldDateKeyTyped(evt);
            }
        });

        hari.setBackground(new java.awt.Color(255, 255, 255));
        hari.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        hari.setForeground(new java.awt.Color(102, 102, 102));
        hari.setText("Hari");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 451,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(kategori)
                                                        .addComponent(periode))
                                                .addGap(97, 97, 97)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnRiview,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 135,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cbKatExport,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 287,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(textFieldDate,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 76,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(hari)))))
                                .addContainerGap(77, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(report)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbKatExport, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kategori))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(periode)
                                        .addComponent(hari))
                                .addGap(40, 40, 40)
                                .addComponent(btnRiview, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(330, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed

    }// GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed

    }// GEN-LAST:event_jButton5ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_jTextField5ActionPerformed

    private void cbKatExportActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbKatExportActionPerformed

    }// GEN-LAST:event_cbKatExportActionPerformed

    private void textFieldDateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldDateActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textFieldDateActionPerformed

    private void textFieldDateKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_textFieldDateKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }

    }// GEN-LAST:event_textFieldDateKeyTyped

    private void btnRiviewActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRiviewActionPerformed
        // TODO add your handling code here:
        Connection conn = DatabaseConfig.connect();
        supplierRepo supplierRepo = new supplierRepo(conn);
        LogStockRepo LogStockRepo = new LogStockRepo(conn);
        transactionsRepo transactionsRepo = new transactionsRepo(conn);

        String kategori = cbKatExport.getSelectedItem().toString();
        int periode = Integer.parseInt(textFieldDate.getText().trim());
        String search = "";

        List<?> data = null;

        try {
            switch (kategori) {
                case "STOCK MASUK":
                    data = LogStockRepo.getList("stock_in", periode, 0, 0);
                    break;
                case "STOCK KELUAR":
                    data = LogStockRepo.getList("stock_out", periode, 0, 0);
                    break;
                case "MASTER SUPPLIER":
                    data = supplierRepo.listSupplier(search, periode, 0, 0);
                    break;
                case "DATA TRANSAKSI":
                    data = transactionsRepo.getAllTransaction(periode, 0, 0);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Silakan pilih kategori terlebih dahulu.");
                    return;
            }

            preview review = new preview(kategori, periode, data);
            review.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }// GEN-LAST:event_btnRiviewActionPerformed

    private void clearInputFields() {
        textFieldDate.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRiview;
    private javax.swing.JComboBox<String> cbKatExport;
    private javax.swing.JLabel hari;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel kategori;
    private javax.swing.JLabel periode;
    private javax.swing.JLabel report;
    private javax.swing.JTextField textFieldDate;
    // End of variables declaration//GEN-END:variables

}