/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.LogStock;
import model.brands;
import model.stock;
import model.items;
import usecase.supplierUc;
import model.suppliers;
import repository.LogStockRepo;
import repository.stocksRepo;
import repository.supplierRepo;
import repository.brandsRepo;
import repository.itemsRepo;
import usecase.BrandUC;
import usecase.itemsUc;
import usecase.logStockUc;
import usecase.stockUc;

/**
 *
 * @author ADMINPUSING-PC
 */
public class StockManagementGUI extends javax.swing.JPanel {
    
    private final supplierUc supplierUc;
    private final BrandUC brandUc;
    private final itemsUc itemsUc;
    private final stockUc stockUc;
    private final logStockUc logStockUc;
    private DefaultTableModel tableModel;
    private int userId = 1;
    
     HashMap<String, Integer> supplierMap= new HashMap<String,Integer>();
     HashMap<String, Integer> brandMap= new HashMap<String,Integer>();
     HashMap<String, Integer> itemMap= new HashMap<String,Integer>();
   
    
    public StockManagementGUI(Connection conn) {
        initComponents();
        
        this.supplierUc = new supplierUc(new supplierRepo(conn), new brandsRepo(conn));
        this.itemsUc = new itemsUc(new itemsRepo(conn), new stocksRepo(conn));
        this.stockUc = new stockUc(new stocksRepo(conn), new itemsRepo(conn));
        this.logStockUc = new logStockUc(new LogStockRepo(conn));
        this.brandUc = new BrandUC(new brandsRepo(conn), new itemsRepo(conn));
        
        this.tableModel = (DefaultTableModel) tLogStock.getModel();

        tableModel = new DefaultTableModel(new Object[][]{}, new String[]{"ID", "Activity Name", "Barang" ,"References(Supplier/TrxId)", "Qty", "Tanggal Dibuat"});
        new JTable(tableModel);
       
        loadCbSuppliers();
        loadLogStock();
      
        textFieldId.setEditable(false);
        textFieldId.setVisible(false);
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldId = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tLogStock = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbItem = new javax.swing.JComboBox<>();
        textFieldQty = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbSupplier = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbBrand = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 255, 204));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(621, 581));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Barang");

        jLabel2.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Supplier");

        textFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(255, 153, 153));
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create");
        btnCreate.setBorder(null);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        tLogStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tLogStock);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setFont(new java.awt.Font("Gill Sans", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("RESTOCK STOK BARANG");

        cbItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbItemActionPerformed(evt);
            }
        });

        textFieldQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldQtyActionPerformed(evt);
            }
        });
        textFieldQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldQtyKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Kuantitas");

        cbSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbSupplierMouseClicked(evt);
            }
        });
        cbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSupplierActionPerformed(evt);
            }
        });
        cbSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbSupplierKeyPressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Merk");

        cbBrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbBrandMouseClicked(evt);
            }
        });
        cbBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBrandActionPerformed(evt);
            }
        });
        cbBrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbBrandKeyPressed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(255, 153, 153));
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Load Data");
        btnRefresh.setBorder(null);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel5)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(426, 426, 426))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(141, 141, 141)
                                                .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel4))
                                                .addGap(88, 88, 88)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(textFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(cbBrand, 0, 266, Short.MAX_VALUE)
                                                        .addComponent(cbItem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel6)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(textFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIdActionPerformed
   
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:   
       
        
        int qty = Integer.parseInt(textFieldQty.getText().trim());
        if(qty<=0){
            JOptionPane.showMessageDialog(this, "Kuantitas tidak boleh kosong.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        stock s = new stock();
        s.setItemId(itemMap.get(cbItem.getSelectedItem().toString()));
        s.setStockIn(qty);
        s.setUpdatedAt(LocalDateTime.now());
        
        LogStock lg = new LogStock();
        lg.setActivityName("stock_in");
        lg.setItemId(itemMap.get(cbItem.getSelectedItem().toString()));
        lg.setRefId(supplierMap.get(cbSupplier.getSelectedItem().toString()));
        lg.setQty(qty);
        lg.setCreatedAt(LocalDateTime.now());
       
        boolean successLg = logStockUc.createLogStock(lg);
        if (!successLg){
            System.out.println("error insert log");
            return;
        }
       
        boolean success = stockUc.updateStockIn(s, 1);
        JOptionPane.showMessageDialog(this, "CREATE: " + (success ? "Berhasil" : "Gagal"));
        if (success) {
            clearInputFields();
            loadLogStock();
            System.out.println("Registrasi brand berhasil!");
        }           
    }//GEN-LAST:event_btnCreateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        loadCbSuppliers();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void cbItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbItemActionPerformed

    }//GEN-LAST:event_cbItemActionPerformed

    private void textFieldQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldQtyActionPerformed

    private void cbSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSupplierActionPerformed
        cbBrand.removeAllItems();
        loadCbBrands();
    }//GEN-LAST:event_cbSupplierActionPerformed

    private void textFieldQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldQtyKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_textFieldQtyKeyTyped

    private void cbBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBrandActionPerformed
        cbItem.removeAllItems();
        loadCbItems();
    }//GEN-LAST:event_cbBrandActionPerformed

    private void cbSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbSupplierMouseClicked
        
    }//GEN-LAST:event_cbSupplierMouseClicked

    private void cbSupplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbSupplierKeyPressed
        
    }//GEN-LAST:event_cbSupplierKeyPressed

    private void cbBrandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbBrandKeyPressed
         
    }//GEN-LAST:event_cbBrandKeyPressed

    private void cbBrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbBrandMouseClicked
       cbItem.removeAll();
    }//GEN-LAST:event_cbBrandMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       loadLogStock();
    }//GEN-LAST:event_btnRefreshActionPerformed
    
    private void clearInputFields() {
        textFieldId.setText("");
        textFieldQty.setText("");
    }
    
    private void loadLogStock(){
        tableModel.setRowCount(0);
        List<LogStock> listLogStock = logStockUc.getList("",0);
        
        for (LogStock s : listLogStock){
            tableModel.addRow(new Object[]{
                s.getId(),
                s.getActivityName(),
                s.getItemName(),
                s.getRefId(),
                s.getQty(),
                s.getCreatedAt(),
            });
        }
        
        tLogStock.setModel(tableModel);

        
    }
    
    private void loadCbSuppliers() {
        List<suppliers> supplierList = supplierUc.getSuppliersList("", 0); 
        
        for (suppliers s : supplierList) {
            supplierMap.put(s.getSupplierName(), s.getId());
            cbSupplier.addItem(s.getSupplierName());  
        }
    }
    
    private void loadCbBrands() {
       String supplierName = cbSupplier.getSelectedItem().toString();
       List<brands> brandList = brandUc.listBrands("",supplierMap.get(supplierName), 0);
        
        for (brands b : brandList) {
            brandMap.put(b.getBrandName(), b.getId());
            cbBrand.addItem(b.getBrandName());  
        }
    }
    
    private void loadCbItems() {
       String brandName = cbBrand.getSelectedItem().toString();
       List<items> itemList = itemsUc.getAllItems("",brandMap.get(brandName));
        
        for (items i : itemList) {
            itemMap.put(i.getItemName(), i.getId());
            cbItem.addItem(i.getItemName());  
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cbBrand;
    private javax.swing.JComboBox<String> cbItem;
    private javax.swing.JComboBox<String> cbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tLogStock;
    private javax.swing.JTextField textFieldId;
    private javax.swing.JTextField textFieldQty;
    // End of variables declaration//GEN-END:variables

}