/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.TransactionDetail;
import model.brands;
import model.items;
import model.stock;
import usecase.supplierUc;
import model.suppliers;
import model.transaction;
import repository.LogStockRepo;
import repository.brandsRepo;
import repository.supplierRepo;
import repository.brandsRepo;
import repository.itemsRepo;
import repository.stocksRepo;
import repository.transactionsDetailRepo;
import repository.transactionsRepo;
import usecase.BrandUC;
import usecase.itemsUc;
import usecase.logStockUc;
import usecase.stockUc;
import usecase.transactionUc;

/**
 *
 * @author ADMINPUSING-PC
 */
public class TransactionManagementGUI extends javax.swing.JPanel {
    
    private final supplierUc supplierUc;
    private final BrandUC brandUc;
    private final itemsUc itemsUc;
    private final stockUc stockUc;
    private final logStockUc logStockUc;
    private final transactionUc transactionUc;
    private DefaultTableModel tableModel;
    private int userId = 1;
    
    HashMap<String, Integer> supplierMap= new HashMap<String,Integer>();
    HashMap<String, Integer> brandMap= new HashMap<String,Integer>();
    HashMap<String, items> itemMap= new HashMap<String,items>();
    
     public List<Object[]> listItems = new ArrayList<>();

    public void tambahData(Object[] data) {
        listItems.add(data);
    }
   
    public TransactionManagementGUI(Connection conn) {
        initComponents();
        
       this.supplierUc = new supplierUc(new supplierRepo(conn), new brandsRepo(conn));
        this.itemsUc = new itemsUc(new itemsRepo(conn), new stocksRepo(conn));
        this.stockUc = new stockUc(new stocksRepo(conn), new itemsRepo(conn));
        this.logStockUc = new logStockUc(new LogStockRepo(conn));
        this.brandUc = new BrandUC(new brandsRepo(conn), new itemsRepo(conn));
        this.transactionUc = new transactionUc(new transactionsRepo(conn), new transactionsDetailRepo(conn), new stocksRepo(conn),new LogStockRepo(conn));
        
        this.tableModel = (DefaultTableModel) tItem.getModel();

        // Initialize the table model
        tableModel = (DefaultTableModel)tItem.getModel();
        new JTable(tableModel);
      
//        loadCbSuppliers();
        
        tItem.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting() && tItem.getSelectedRow() != -1) {
                    int selectedRow = tItem.getSelectedRow();
                    textFieldTrxId.setText(String.valueOf(selectedRow));
                    loadCbSuppliers();
                }
            }
        });
      
        textFieldTrxId.setEditable(false);
        textFieldTrxId.setVisible(false);
        
        labelGrandTotal.setText("0");
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        textFieldTrxId = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tItem = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        cbBrand = new javax.swing.JComboBox<>();
        cbItem = new javax.swing.JComboBox<>();
        textFieldQty = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbSupplier = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelGrandTotal = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 255, 204));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(621, 581));

        textFieldTrxId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTrxIdActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(255, 153, 153));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add Item");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 153, 153));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(null);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 153, 153));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Item");
        btnDelete.setBorder(null);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Barang", "Merk", "Supplier", "Qty", "Harga", "Total Harga"
            }
        ));
        jScrollPane2.setViewportView(tItem);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setFont(new java.awt.Font("Gill Sans", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("TRANSACTION");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));

        btnCancel.setBackground(new java.awt.Color(255, 153, 153));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        cbBrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbBrandMouseClicked(evt);
            }
        });
        cbBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBrandActionPerformed(evt);
            }
        });
        cbBrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbBrandKeyPressed(evt);
            }
        });

        cbItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbItemActionPerformed(evt);
            }
        });

        textFieldQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldQtyActionPerformed(evt);
            }
        });
        textFieldQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldQtyKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Kuantitas");

        cbSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbSupplierMouseClicked(evt);
            }
        });
        cbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSupplierActionPerformed(evt);
            }
        });
        cbSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbSupplierKeyPressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Merk");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Barang");

        jLabel9.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Supplier");

        jLabel1.setText("GRAND TOTAL");

        labelGrandTotal.setText("GRAND TOTAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textFieldTrxId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel9))
                                            .addGap(88, 88, 88)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cbItem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbSupplier, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbBrand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(textFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(142, 142, 142)
                                    .addComponent(jLabel5)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(1313, 1313, 1313)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(348, 348, 348)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(36, 36, 36)
                                    .addComponent(labelGrandTotal))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(textFieldTrxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelGrandTotal))
                .addGap(129, 129, 129)
                .addComponent(jLabel5)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldTrxIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTrxIdActionPerformed
        
    }//GEN-LAST:event_textFieldTrxIdActionPerformed
   
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    double price = itemMap.get(cbItem.getSelectedItem().toString()).getPrice();
    int qty =Integer.parseInt(textFieldQty.getText());
    
    System.out.println("price :" + price);
    System.out.println("qty :" + qty);
    
    double totalPrice = price * qty;
    
    System.out.println("total price :" + totalPrice);
        
    listItems.add(new Object[]{
        cbItem.getSelectedItem().toString(),
        cbBrand.getSelectedItem().toString(),
        cbSupplier.getSelectedItem().toString(),
        qty,
        price,
        totalPrice,
    });

    loadTableModel();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        listItems.remove(Integer.parseInt(textFieldTrxId.getText())-1);
        loadTableModel();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      DefaultTableModel model = (DefaultTableModel) tItem.getModel();
      int rowCount = model.getRowCount();
      int colCount = model.getColumnCount();
      
      if (rowCount == 0){
          JOptionPane.showMessageDialog(this, "tidak ada item untuk di simpan", "Error", JOptionPane.ERROR_MESSAGE);
          return;
      }
      
      transaction trx = new transaction();
      trx.setDate(LocalDate.now());
      trx.setGrandTotal(Double.parseDouble(labelGrandTotal.getText()));
      trx.setCreatedAt(LocalDateTime.now());
      trx.setTotalItem(rowCount);
      trx.setCreatedBy(1);
      
      Integer trxId = transactionUc.createTransaction(trx);
      if (trxId == 0) {
        JOptionPane.showMessageDialog(this, "gagal menyimpan transaksi", "Error", JOptionPane.ERROR_MESSAGE);
        return;
      }

        for (int i = 0; i < rowCount; i++) {
         System.out.println("Row ke-" + (i + 1));
         
         TransactionDetail td = new TransactionDetail();
         td.setTransactionId(trxId);
         td.setItemId(itemMap.get(model.getValueAt(i, 1).toString()).getId());
         td.setQty(Integer.parseInt(model.getValueAt(i, 4).toString()));
         td.setPrice(Double.parseDouble(model.getValueAt(i, 6).toString()));
         td.setCreatedAt(LocalDateTime.now());
         td.setCreatedBy(1);
         
        
        boolean success = transactionUc.createDetailTransaction(td);
        if (!success) {
            JOptionPane.showMessageDialog(this, "CREATE: " + (success ? "Berhasil" : "Gagal"));
            clearInputFields();
            tItem.removeAll();
            return;
            }     
        }
        
         clearInputFields();
         model.setRowCount(0); // clear data table
        listItems.clear(); 
        
        System.out.println("berhasil!");
         JOptionPane.showMessageDialog(this, "CREATE: " + (true ? "Berhasil" : "Gagal"));
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbBrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbBrandMouseClicked
     
    }//GEN-LAST:event_cbBrandMouseClicked

    private void cbBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBrandActionPerformed

        cbItem.removeAllItems();
        loadCbItems();
    }//GEN-LAST:event_cbBrandActionPerformed

    private void cbBrandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbBrandKeyPressed

    }//GEN-LAST:event_cbBrandKeyPressed

    private void cbItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbItemActionPerformed
        
    }//GEN-LAST:event_cbItemActionPerformed

    private void textFieldQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldQtyActionPerformed

    private void textFieldQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldQtyKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_textFieldQtyKeyTyped

    private void cbSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbSupplierMouseClicked
        cbSupplier.removeAll();
        loadCbSuppliers();
    }//GEN-LAST:event_cbSupplierMouseClicked

    private void cbSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSupplierActionPerformed
        cbBrand.removeAllItems();
        loadCbBrands();
    }//GEN-LAST:event_cbSupplierActionPerformed

    private void cbSupplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbSupplierKeyPressed

    }//GEN-LAST:event_cbSupplierKeyPressed
    
    private void clearInputFields() {
        textFieldTrxId.setText("");
        textFieldQty.setText("");
    }
    
    
    private void loadTableModel() {
        tableModel.setRowCount(0); // clear table
        double grandTotal = 0;
        
        int no = 1;
        for (Object[] row : listItems) {
            Object[] rowWithNo = new Object[row.length + 1];
            rowWithNo[0] = no++;
            System.arraycopy(row, 0, rowWithNo, 1, row.length);
            grandTotal += Double.parseDouble(rowWithNo[6].toString());
        tableModel.addRow(rowWithNo);
        }
        
        labelGrandTotal.setText(String.valueOf(grandTotal));
}
    
    private void loadCbSuppliers() {
        List<suppliers> supplierList = supplierUc.getSuppliersList("", 0); 
        
        for (suppliers s : supplierList) {
            supplierMap.put(s.getSupplierName(), s.getId());
            cbSupplier.addItem(s.getSupplierName());  
        }
    }
    
    private void loadCbBrands() {
       Object selectedBrand = cbSupplier.getSelectedItem();
       if (selectedBrand == null) return;
       
       String supplierName = cbSupplier.getSelectedItem().toString();
       List<brands> brandList = brandUc.listBrands("",supplierMap.get(supplierName),0);
        
        for (brands b : brandList) {
            brandMap.put(b.getBrandName(), b.getId());
            cbBrand.addItem(b.getBrandName());  
        }
    }
    
    private void loadCbItems() {
        Object selectedBrand = cbBrand.getSelectedItem();
        if (selectedBrand == null) return; 
        
       String brandName = cbBrand.getSelectedItem().toString();
       List<items> itemList = itemsUc.getAllItems("",brandMap.get(brandName));  
       
        for (items i : itemList) {
            itemMap.put(i.getItemName(), i);
            cbItem.addItem(i.getItemName());  
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbBrand;
    private javax.swing.JComboBox<String> cbItem;
    private javax.swing.JComboBox<String> cbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelGrandTotal;
    private javax.swing.JTable tItem;
    private javax.swing.JTextField textFieldQty;
    private javax.swing.JTextField textFieldTrxId;
    // End of variables declaration//GEN-END:variables

}