/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.TransactionDetail;
import model.brands;
import model.items;

import usecase.supplierUc;
import model.suppliers;
import model.transaction;
import repository.LogStockRepo;
import repository.brandsRepo;
import repository.supplierRepo;
import repository.brandsRepo;
import repository.itemsRepo;
import repository.stocksRepo;
import repository.transactionsDetailRepo;
import repository.transactionsRepo;
import usecase.BrandUC;
import usecase.itemsUc;

import usecase.transactionUc;

/**
 *
 * @author ADMINPUSING-PC
 */
public class TransactionManagementGUI extends javax.swing.JPanel {

    private final supplierUc supplierUc;
    private final BrandUC brandUc;
    private final itemsUc itemsUc;

    private final transactionUc transactionUc;
    private DefaultTableModel tableModel;

    HashMap<String, Integer> supplierMap = new HashMap<String, Integer>();
    HashMap<String, Integer> brandMap = new HashMap<String, Integer>();
    HashMap<String, items> itemMap = new HashMap<String, items>();

    public List<Object[]> listItems = new ArrayList<>();

    public void tambahData(Object[] data) {
        listItems.add(data);
    }

    public TransactionManagementGUI(Connection conn) {
        initPaginationComponents();
        initComponents();

        this.supplierUc = new supplierUc(new supplierRepo(conn), new brandsRepo(conn));
        this.itemsUc = new itemsUc(new itemsRepo(conn), new stocksRepo(conn));

        this.brandUc = new BrandUC(new brandsRepo(conn), new itemsRepo(conn));
        this.transactionUc = new transactionUc(new transactionsRepo(conn), new transactionsDetailRepo(conn),
                new stocksRepo(conn), new LogStockRepo(conn));

        this.tableModel = (DefaultTableModel) tItem.getModel();

        // Initialize the table model
        tableModel = (DefaultTableModel) tItem.getModel();
        new JTable(tableModel);

        loadCbSuppliers();

        tItem.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting() && tItem.getSelectedRow() != -1) {
                    int selectedRow = tItem.getSelectedRow();
                    textFieldTrxId.setText(String.valueOf(selectedRow));
                    loadCbSuppliers();
                }
            }
        });

        textFieldTrxId.setEditable(false);
        textFieldTrxId.setVisible(false);

        labelGrandTotal.setText("0");

        labelGrandTotal.setText("0");

        // Clear initial table data
        ((DefaultTableModel) tItem.getModel()).setRowCount(0);

        helper.TableUtils.styleTable(tItem);
        helper.TableUtils.styleTable(jTable1);
    }

    private int currentPage = 1;
    private int limit = 10;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel labelPage;

    private void initPaginationComponents() {
        btnPrev = new javax.swing.JButton("< Previous");
        btnNext = new javax.swing.JButton("Next >");
        labelPage = new javax.swing.JLabel("Page: 1");

        btnPrev.addActionListener(e -> {
            if (currentPage > 1) {
                currentPage--;
                loadTransactions();
            }
        });

        btnNext.addActionListener(e -> {
            currentPage++;
            loadTransactions();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        textFieldTrxId = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tItem = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        cbBrand = new javax.swing.JComboBox<>();
        cbItem = new javax.swing.JComboBox<>();
        textFieldQty = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbSupplier = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelGrandTotal = new javax.swing.JLabel();
        labelRangeDay = new javax.swing.JLabel();
        textRangeDay = new javax.swing.JTextField();
        btnLoadData = new javax.swing.JButton();

        // Transaction History Table
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] {
                        "ID", "Date", "Grand Total", "Total Item", "Admin"
                }));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 255, 204));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(900, 750));

        textFieldTrxId.setEditable(false);
        textFieldTrxId.setVisible(false);
        textFieldTrxId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTrxIdActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(255, 153, 153));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add Item");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 153, 153));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save Transaction");
        btnSave.setBorder(null);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 153, 153));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Item");
        btnDelete.setBorder(null);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        // Cart Table
        tItem.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] {
                        "No", "Nama Barang", "Merk", "Supplier", "Qty", "Harga", "Total Harga"
                }));
        jScrollPane2.setViewportView(tItem);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setFont(new java.awt.Font("Gill Sans", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("TRANSACTION MANAGEMENT");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));

        btnCancel.setBackground(new java.awt.Color(255, 153, 153));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        cbBrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbBrandMouseClicked(evt);
            }
        });
        cbBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBrandActionPerformed(evt);
            }
        });
        cbBrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbBrandKeyPressed(evt);
            }
        });

        cbItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbItemActionPerformed(evt);
            }
        });

        textFieldQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldQtyActionPerformed(evt);
            }
        });
        textFieldQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldQtyKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Kuantitas");

        cbSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbSupplierMouseClicked(evt);
            }
        });
        cbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSupplierActionPerformed(evt);
            }
        });
        cbSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbSupplierKeyPressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Merk");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Barang");

        jLabel9.setFont(new java.awt.Font("Gill Sans", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Supplier");

        jLabel1.setFont(new java.awt.Font("Gill Sans", 1, 14));
        jLabel1.setText("GRAND TOTAL:");

        labelGrandTotal.setFont(new java.awt.Font("Gill Sans", 1, 14));
        labelGrandTotal.setText("0");

        labelRangeDay.setFont(new java.awt.Font("Gill Sans", 0, 14));
        labelRangeDay.setText("Range Day:");
        textRangeDay.setText("1");

        btnLoadData.setText("Load Data");
        btnLoadData.setBackground(new java.awt.Color(255, 153, 153));
        btnLoadData.setForeground(new java.awt.Color(255, 255, 255));
        btnLoadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 600,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnPrev)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(labelPage)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnNext)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel9)
                                                                        .addComponent(jLabel8)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel7))
                                                                .addGap(43, 43, 43)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(cbSupplier, 0, 400,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(cbBrand, 0,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(cbItem, 0,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(textFieldQty)
                                                                        .addComponent(textFieldTrxId,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                46,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btnAdd,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                135,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(350, 350, 350))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(labelRangeDay)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(textRangeDay,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        50,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(btnLoadData,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        135,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(btnDelete,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        135,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(btnSave,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        135,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(btnCancel,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        135,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(50, 50, 50)
                                                                                .addComponent(jLabel1)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(labelGrandTotal,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        150,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(40, 40, 40)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(cbBrand, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(cbItem, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(textFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldTrxId, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(labelGrandTotal))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnLoadData)
                                        .addComponent(textRangeDay, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelRangeDay))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnPrev)
                                        .addComponent(labelPage)
                                        .addComponent(btnNext))
                                .addContainerGap(40, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldTrxIdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldTrxIdActionPerformed

    }// GEN-LAST:event_textFieldTrxIdActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
        double price = itemMap.get(cbItem.getSelectedItem().toString()).getPrice();
        int qty = Integer.parseInt(textFieldQty.getText());

        System.out.println("price :" + price);
        System.out.println("qty :" + qty);

        double totalPrice = price * qty;

        System.out.println("total price :" + totalPrice);

        listItems.add(new Object[] {
                cbItem.getSelectedItem().toString(),
                cbBrand.getSelectedItem().toString(),
                cbSupplier.getSelectedItem().toString(),
                qty,
                price,
                totalPrice,
        });

        loadTableModel();

    }// GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        String trxIdText = textFieldTrxId.getText();
        if (trxIdText == null || trxIdText.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select an item to delete.", "Warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int index = Integer.parseInt(trxIdText) - 1;
            if (index >= 0 && index < listItems.size()) {
                listItems.remove(index);
                loadTableModel();
                textFieldTrxId.setText(""); // Reset selection
            } else {
                JOptionPane.showMessageDialog(this, "Invalid item selection.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid ID format.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed
        DefaultTableModel model = (DefaultTableModel) tItem.getModel();
        int rowCount = model.getRowCount();

        if (rowCount == 0) {
            JOptionPane.showMessageDialog(this, "tidak ada item untuk di simpan", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        transaction trx = new transaction();
        trx.setDate(LocalDate.now());
        trx.setGrandTotal(Double.parseDouble(labelGrandTotal.getText()));
        trx.setCreatedAt(LocalDateTime.now());
        trx.setTotalItem(rowCount);
        trx.setCreatedBy(1);

        Integer trxId = transactionUc.createTransaction(trx);
        if (trxId == 0) {
            JOptionPane.showMessageDialog(this, "gagal menyimpan transaksi", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (int i = 0; i < rowCount; i++) {
            System.out.println("Row ke-" + (i + 1));

            TransactionDetail td = new TransactionDetail();
            td.setTransactionId(trxId);

            Object itemNameObj = model.getValueAt(i, 1);
            if (itemNameObj == null) {
                JOptionPane.showMessageDialog(this, "Item name missing at row " + (i + 1), "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            String itemName = itemNameObj.toString();

            items itemObj = itemMap.get(itemName);
            if (itemObj == null) {
                // Try to recover from itemsUc if map is missing it (edge case)
                // But for now, just show error
                JOptionPane.showMessageDialog(this, "Item data not found for: " + itemName, "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            td.setItemId(itemObj.getId());
            td.setQty(Integer.parseInt(model.getValueAt(i, 4).toString()));
            td.setPrice(Double.parseDouble(model.getValueAt(i, 6).toString()));
            td.setCreatedAt(LocalDateTime.now());
            td.setCreatedBy(1);

            boolean success = transactionUc.createDetailTransaction(td);
            if (!success) {
                JOptionPane.showMessageDialog(this, "CREATE: " + (success ? "Berhasil" : "Gagal"));
                clearInputFields();
                tItem.removeAll();
                return;
            }
        }

        clearInputFields();
        model.setRowCount(0); // clear data table
        listItems.clear();

        System.out.println("berhasil!");
        JOptionPane.showMessageDialog(this, "CREATE: " + (true ? "Berhasil" : "Gagal"));
    }// GEN-LAST:event_btnSaveActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_jTextField5ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnCancelActionPerformed

    private void cbBrandMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_cbBrandMouseClicked

    }// GEN-LAST:event_cbBrandMouseClicked

    private void cbBrandActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbBrandActionPerformed

        cbItem.removeAllItems();
        loadCbItems();
    }// GEN-LAST:event_cbBrandActionPerformed

    private void cbBrandKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_cbBrandKeyPressed

    }// GEN-LAST:event_cbBrandKeyPressed

    private void cbItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbItemActionPerformed

    }// GEN-LAST:event_cbItemActionPerformed

    private void textFieldQtyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldQtyActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textFieldQtyActionPerformed

    private void textFieldQtyKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_textFieldQtyKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }// GEN-LAST:event_textFieldQtyKeyTyped

    private void cbSupplierMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_cbSupplierMouseClicked
        cbSupplier.removeAllItems();
        supplierMap.clear();
        loadCbSuppliers();
    }// GEN-LAST:event_cbSupplierMouseClicked

    private void cbSupplierActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbSupplierActionPerformed
        cbBrand.removeAllItems();
        loadCbBrands();
    }// GEN-LAST:event_cbSupplierActionPerformed

    private void cbSupplierKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_cbSupplierKeyPressed

    }// GEN-LAST:event_cbSupplierKeyPressed

    private void btnLoadDataActionPerformed(java.awt.event.ActionEvent evt) {
        currentPage = 1;
        loadTransactions();
    }

    private void loadTransactions() {
        try {
            String rangeText = textRangeDay.getText();
            int range = 0;
            if (rangeText != null && !rangeText.trim().isEmpty()) {
                range = Integer.parseInt(rangeText);
            }

            // Fetch data
            int offset = (currentPage - 1) * limit;
            List<transaction> list = transactionUc.getTransactionList(range, limit, offset);

            if (labelPage != null) {
                labelPage.setText("Page: " + currentPage);
            }

            // Update Table
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            for (transaction t : list) {
                model.addRow(new Object[] {
                        t.getId(),
                        t.getDate(),
                        t.getGrandTotal(),
                        t.getTotalItem(),
                        t.getUsername()
                });
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Range Day format", "Error", JOptionPane.ERROR_MESSAGE);
            // Revert to 0 or something safe?
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to load data: " + e.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearInputFields() {
        textFieldTrxId.setText("");
        textFieldQty.setText("");
    }

    private void loadTableModel() {
        tableModel.setRowCount(0); // clear table
        double grandTotal = 0;

        int no = 1;
        for (Object[] row : listItems) {
            Object[] rowWithNo = new Object[row.length + 1];
            rowWithNo[0] = no++;
            System.arraycopy(row, 0, rowWithNo, 1, row.length);
            grandTotal += Double.parseDouble(rowWithNo[6].toString());
            tableModel.addRow(rowWithNo);
        }

        labelGrandTotal.setText(String.valueOf(grandTotal));
    }

    private void loadCbSuppliers() {
        List<suppliers> supplierList = supplierUc.getSuppliersList("", 0, 0, 0);

        for (suppliers s : supplierList) {
            supplierMap.put(s.getSupplierName(), s.getId());
            cbSupplier.addItem(s.getSupplierName());
        }
    }

    private void loadCbBrands() {
        Object selectedBrand = cbSupplier.getSelectedItem();
        if (selectedBrand == null)
            return;

        String supplierName = cbSupplier.getSelectedItem().toString();
        List<brands> brandList = brandUc.listBrands("", supplierMap.get(supplierName), 0, 0, 0);

        for (brands b : brandList) {
            brandMap.put(b.getBrandName(), b.getId());
            cbBrand.addItem(b.getBrandName());
        }
    }

    private void loadCbItems() {
        Object selectedBrand = cbBrand.getSelectedItem();
        if (selectedBrand == null)
            return;

        String brandName = cbBrand.getSelectedItem().toString();
        List<items> itemList = itemsUc.getAllItems("", brandMap.get(brandName), 0, 0);

        for (items i : itemList) {
            itemMap.put(i.getItemName(), i);
            cbItem.addItem(i.getItemName());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbBrand;
    private javax.swing.JComboBox<String> cbItem;
    private javax.swing.JComboBox<String> cbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelGrandTotal;
    private javax.swing.JTable tItem;
    private javax.swing.JTextField textFieldQty;
    private javax.swing.JTextField textFieldTrxId;

    private javax.swing.JLabel labelRangeDay;
    private javax.swing.JTextField textRangeDay;
    private javax.swing.JButton btnLoadData;
    // End of variables declaration//GEN-END:variables

}